title: Hessen mit Kids
email: info@hessenmitkids.de
description: >-
  Hessen mit Kids: Spielplätze, Schwimmbäder, Parks uvm.
baseurl: ""
url: https://hessenmitkids.de
permalink: /:categories/:slug
theme: minima
minima:
  skin: auto
plugins:
  - jekyll-feed